name = "Loom"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Loom"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "1755c0ff6d14a8b7818003c6f277a4410c2683bd"

[[lean_lib]]
name = "Loom"
